DROP DATABASE IF EXISTS PAGAMENTOS;

CREATE DATABASE PAGAMENTOS;

USE PAGAMENTOS;

CREATE LOTACAO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(45),
	sigla CHAR(11),
	idlotacao INT NOT NULL,
	idfuncionario_responsavel INT NOT NULL,
	FOREIGN KEY (idfuncionario_responsavel) REFERENCES EMPREGADO (id)
);

CREATE EMPREGADO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(45),
	cpf CHAR(11),
	sexo ENUM('M','F'),
	idade INT NOT NULL,
	salarioBruto DOUBLE NOT NULL,
	descontosImpostoRenda DOUBLE NOT NULL,
	contribuicaoPevidenciaria DOUBLE NOT NULL,
	salarioBase DOUBLE NOT NULL,
	idLotacao int NOT NULL,
	cargo VARCHAR(20),
	FOREIGN KEY (idLotacao) REFERENCES LOTACAO (id)
);




