CREATE DATABASE PAGAMENTOS;

USE PAGAMENTOS;

CREATE OPERACIONAL (
	IDOPERACIONAL INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45),
	CPF CHAR(11),
	SEXO ENUM('M','F'),
	idade INT NOT NULL,
	SALARIOBRUTO INT NOT NULL,
	DESCONTOSIMPOSTODERENDA INT NOT NULL,
	CONTRIBUICAOPREVIDENCIARIA INT NOT NULL,
);



CREATE GERENTE (
	IDGERENTE INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45),
	CPF CHAR(11),
	SEXO ENUM('M','F'),
	idade INT NOT NULL,
	SALARIOBRUTO INT NOT NULL,
	DESCONTOSIMPOSTODERENDA INT NOT NULL,
	CONTRIBUICAOPREVIDENCIARIA INT NOT NULL,
	FOREIGN KEY (IDOPERACIONAL) REFERENCES OPERACIONAL (IDOPERACIONAL)
);

CREATE DIRETORIA (
	IDDIRETOR INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45),
	CPF CHAR(11),
	SEXO ENUM('M','F'),
	idade INT NOT NULL,
	SALARIOBRUTO INT NOT NULL,
	DESCONTOSIMPOSTODERENDA INT NOT NULL,
	CONTRIBUICAOPREVIDENCIARIA INT NOT NULL,
	FOREIGN KEY (IDGERENTE) REFERENCES GERENTE (IDGERENTE)
);





